### ISSUE TITLE
Error with oxford_asl --iaf option

### ISSUE THREAD

**Issue by YukoNakamuraDDS** [ibme-qubic/oxford_asl#6]
Dear Experts,

To practice asl analysis, I downloaded sample data (singlePLDpcASL) from BASIL website and tried to run oxford_asl.
I tried to run the following line as the website showed.
oxford_asl -i asltc -o oxasl --wp --casl --iaf=tc --tis=3.6 --bolus=1.8 --slicedt=0.0452 --spatial --moco -c aslcalib --tr 4.8 --cblip=aslcalib_PA --pedir=y --echospacing=0.06

Then I've got the following error.
Error! Unrecognised option on command line: --iaf

I searched oxford_asl file and checked it if it would have --iaf option. Then I've found it in the file.

My environment is the following.
I downloaded the latest version of oxford_asl (from this website; 
https://github.com/ibme-qubic/oxford_asl/files/2302429/oxford_asl-3.9.17-osx.tar.gz) and overwrite it on the old version of oxford_asl.

I also installed wxpython, matplotlib, numpy and nibabel, and checked fslpython (it worked). So I'm wondering if someone would have any idea about this error (--iaf option problem).

Thank you so much for your time.

Best wishes,
Yuko

**Comment by mcraig-ibme** [comment]
Hi, apologies for the lack of response, I have not been getting GitHub notifications and a number of issues have been raised here without me realising.

If this issue is still present in current versions of oxford_asl (FSL 6.0.1 or later) then please let me know - otherwise I will close the issue. --iaf should definitely be recognized as an option.

**Comment by mcraig-ibme** [comment]
Closing historical issue
